apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  namespace: internal-logging
data:
  cluster.name: k8s-logs
  discovery.seed_hosts: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
  cluster.initial_master_nodes: "es-cluster-0,es-cluster-1,es-cluster-2"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"