apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: internal-logging
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rest
      port: 9200
    - name: inter-communication
      port: 9300

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: internal-logging
  
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch

    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          envFrom:
            - configMapRef:
                name: elasticsearch-configmap
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data

      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
            
    
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi