apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-search-configmap
  namespace: internal-logging
data:
  cluster.name: k8s-logs
  discovery.seed_hosts: "es-cluster-0.elastic-search,es-cluster-1.elastic-search,es-cluster-2.elastic-search"
  cluster.initial_master_nodes: "es-cluster-0,es-cluster-1,es-cluster-2"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"